---

- name: Remove YUM repositories
  hosts: all
  become: true

  tasks:
  - name: Remove repository (and clean up left-over metadata)
    shell: yum-config-manager --disable {{item}}
    with_items:
      - elrepo-kernel
      - docker-ce-stable
      - docker-ce-edge
      - docker-ce-edge-debuginfo
      - docker-ce-edge-source
      - docker-ce-nightly
      - docker-ce-nightly-debuginfo
      - docker-ce-nightly-source
      - docker-ce-stable
      - docker-ce-stable-debuginfo
      - docker-ce-stable-source
      - docker-ce-test
      - docker-ce-test-debuginfo
      - docker-ce-test-source
      - kubernetes

