---

- name: Installing Kubelet, kubeadm and kubectl
  hosts: all
  become: yes

  tasks:
    - name: Removing packages
      yum:
        name: ['kubelet', 'kubeadm', 'kubectl']
        state: removed

    - name: Add an rpm signing key for Kubernetes
      rpm_key:
        state: present
        key: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - name: Adding another key
      rpm_key:
        state: present
        key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Adding YUM repository for Kubernetes
      yum_repository:
        name: kubernetes
        description: kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: 1
        gpgcheck: yes

    - name: Install Kubernetes binaries
      yum:
        name: [ "kubelet" ,"kubeadm", "kubectl" ]
        state: present

#    - name: Configure node ip
#      lineinfile:
#        path: /etc/default/kubelet
#        line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Remove repository (and clean up left-over metadata)
      yum_repository:
        name: [ 'elrepo-kernel', 'elrepo', 'docker-ce', 'kubernetes' ]
        state: absent
        enabled: 0
      notify: yum-clean-metadata

